# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    webp:
        generate: true
        quality: 100
        cache: ~
        data_loader: ~
        post_processors: []

    controller:
        redirect_response_code: 302
    twig:
        mode: lazy

    filter_sets:
        cache: ~
        homepage_large:
            quality: 100
            # format: webp
            filters:
                thumbnail:
                    size: [1000, 563]
                    mode: outbound

        homepage_medium:
            quality: 100
            # format: webp
            filters:
                thumbnail:
                    size: [750, 422]
                    mode: outbound

        homepage_small:
            # quality: 100
            format: webp
            filters:
                crop:
                    size: [500, 281]
                    start: [ 040, 160 ]
                    # mode: outbound

        homepage_thumbnail:
            quality: 100
            # format: webp
            filters:
                thumbnail:
                    size: [369, 192]
                    mode: outbound

        homepage_thumbnail_large:
            quality: 100
            # format: webp
            filters:
                thumbnail:
                    size: [745, 390]
                    mode: outbound

        homepage_thumbnail_small:
            quality: 100
            # format: webp
            filters:
                thumbnail:
                    size: [372, 192]
                    mode: outbound

        blog_large:
            quality: 75
            filters:
                thumbnail:
                    size: [1000, 563]
                    mode: outbound

        blog_medium:
            quality: 75
            filters:
                thumbnail:
                    size: [750, 422]
                    mode: outbound

        blog_small:
            quality: 75
            filters:
                thumbnail:
                    size: [500, 281]
                    mode: outbound

        blog_thumbnail:
            format: webp
            quality: 75
            filters:
                thumbnail:
                    size: [370, 256]
                    mode: outbound

        blog_show:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [1903, 332] }
                # background:
                #     {size: [1903, 332], position: center }

        post_thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound

        post_sidebar:
            quality: 75
            filters:
                thumbnail:
                    size: [60, 60]
                    mode: outbound

        admin_post_thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound

        user_thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [96, 96]
                    mode: outbound

        avatar:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [40, 40]
                    mode: outbound

        avatar_comment:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [33, 33]
                    mode: outbound
        profil:
            quality: 75
            filters:
                thumbnail:
                    size: [226, 226]
                    mode: outbound

        streamer:
            quality: 75
            filters:
                thumbnail:
                    size: [48, 48]

        gallery_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [316, 183]
                    mode: outbound

        filebrowser:
            quality: 75
            filters:
                thumbnail:
                    size: [509, 332]
                    mode: outbound
