version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - 8000:8000
    volumes:
        - .:/var/www:delegated
        - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
        # - ./tools/nginx/.htpasswd:/etc/nginx/.htpasswd
        - ./tools/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - "php-fpm"
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
        - "traefik.http.routers.nest-gaming-https.rule=Host(`${DOMAIN_NAME:-www.nest-gaming.local}`)"
        - "traefik.http.routers.nest-gaming-https.entrypoints=web-secure"
        - "traefik.http.routers.nest-gaming-https.tls=true"
        - "traefik.http.routers.nest-gaming-https.tls.certresolver=${CERT:-default}"
        - "traefik.http.routers.nest-gaming-https.service=nest-gaming"
        - "traefik.http.routers.nest-gaming-http.rule=Host(`${DOMAIN_NAME:-www.nest-gaming.local}`)"
        - "traefik.http.routers.nest-gaming-http.entrypoints=web"
        - "traefik.http.routers.nest-gaming-http.middlewares=redirect-https"
        - "traefik.http.routers.nest-gaming-http.service=nest-gaming"
        - "traefik.http.services.nest-gaming.loadbalancer.server.port=8000"
        - "com.centurylinklabs.watchtower.enable=true"
    networks:
        - web
        - private
        
  php-fpm:
    container_name: php-fpm
    user: "${USER_ID}:${GROUP_ID}"
    restart: unless-stopped
    image: oliviermj/php8.0-fpm-dev-symfony-xdebug:latest
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
      - redis
      - typesense
    links:
      - database
      - typesense
    environment:
      APP_ENV: dev
      TZ: Europe/Paris
      REDIS_URL: redis://cache
      TYPESENSE_KEY: typesense
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: 8108
      DATABASE_URL: "mysql://nest:nest@database:3306/nest?serverVersion=mariadb-10.5.9"
      MERCURE_URL: 'https://127.0.0.1:8000/.well-known/mercure'
      MERCURE_PUBLIC_URL: 'https://127.0.0.1:8000/.well-known/mercure'
      MERCURE_JWT_SECRET: '!ChangeMe!'
      GLIDE_KEY: "0c2a58ee69754b068a7f4265180f781225575465e6408c1383498bd529a37550"
      TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR, 192.168.1.0/24, www.nest-gaming.fr, nest-gaming.fr, beta.nest-gaming.fr"
      DISQUS_PRIVATE_KEY: "VnrnRsTnQlCPDjCROnMkD9YxwNZXLSNxt9BNloTY1XlPqY4ElloVDPbSKGDCAfxb"
      DISQUS_PUBLIC_KEY: "gA3E6u1xLq3CDb8YxfL3dZN22Z4ReKmZlL8X9vH7mEh0y6AJaRyQy4wuZoerWQND"
    networks:
      - private
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"

  php:
    container_name: php
    image: php:8.0.13-cli
    user: "${USER_ID}:${GROUP_ID}"
    # image: oliviermj/php8.0-fpm-dev-symfony-xdebug:latest
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
      - redis
      - typesense
    links:
      - database
      - typesense
    environment:
      TZ: Europe/Paris
      PHP_IDE_CONFIG: serverName=nest
      APP_ENV: dev
      REDIS_URL: redis://redis
      TYPESENSE_KEY: typesense
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: 8108
      DATABASE_URL: mysql://nest:nest@localhost:3306/nest?serverVersion=mariadb-10.5.9
    networks:
      - private

  database:
    restart: unless-stopped
    image: 'mariadb:latest'
    container_name: database
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_DATABASE: nest
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - private

  typesense:
    restart: unless-stopped
    image: typesense/typesense:0.22.0
    container_name: typesense
    command: "--enable-cors"
    environment:
      TZ: Europe/Paris
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesense
      CORS: enable
    volumes:
      - data-search:/data
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - private
      - web

  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:6-alpine
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - private



volumes:
  ###> doctrine/doctrine-bundle ###
  database:
        name: database
  data-search:
      name: data-search
      driver: local
  ###< doctrine/doctrine-bundle ###


networks:
  web:
    external: true
    name: web
  private:
    internal: true
    name: private
    driver: bridge
